
jwt.secretKey: skjdsnoi34$OWED*(@ENOSENDKNZDlxndsljfscbkxjfbskjfbzkxmzxclxcjnsf

spring:
  application:
    name: api-gateway


  server:
    port: 8080

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
  cloud:
    gateway:
          routes:
            - id: user-services
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/v1/users/**
              filters:
                - StripPrefix=2

            - id: post-service
              uri: lb://POST-SERVICE
              predicates:
                - Path=/api/v1/posts/**
              filters:
                - StripPrefix=2
                - name: AuthenticationFilter

            - id: connections-service
              uri: lb://CONNECTIONS-SERVICE
              predicates:
                - Path=/api/v1/connections/**
              filters:
                - StripPrefix=2
                - name: AuthenticationFilter

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    urls:
      - name: connections-service
        url: api/v1/connections/api-docs
      - name: post-service
        url: api/v1/posts/api-docs
      - name: user-services
        url: api/v1/users/api-docs